// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://judcctpdxqdrzyatusid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1ZGNjdHBkeHFkcnp5YXR1c2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODgyMjgsImV4cCI6MjA3NDA2NDIyOH0.uyoT2fHEtfQYT7taVgtNug6Hq-rh7PLl9ZjogvH8Chk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});